// <auto-generated />
using System;
using AircraftService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AircraftService.Migrations
{
    [DbContext(typeof(AircraftDbContext))]
    [Migration("20241018101057_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AircraftService.Models.Entities.Aircraft", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("FuelCapacity")
                        .HasColumnType("float");

                    b.Property<int>("FuelManagementId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Registration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FuelManagementId");

                    b.ToTable("Aircrafts");
                });

            modelBuilder.Entity("AircraftService.Models.Entities.FuelManagementData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double>("FuelOnBoard")
                        .HasColumnType("float");

                    b.Property<DateTime>("LastRefueled")
                        .HasColumnType("datetime2");

                    b.Property<double>("PlannedUplift")
                        .HasColumnType("float");

                    b.Property<double>("RecentUplift")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("FuelManagementData");
                });

            modelBuilder.Entity("AircraftService.Models.Entities.Aircraft", b =>
                {
                    b.HasOne("AircraftService.Models.Entities.FuelManagementData", "FuelManagement")
                        .WithMany()
                        .HasForeignKey("FuelManagementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FuelManagement");
                });
#pragma warning restore 612, 618
        }
    }
}
